// Generates the authentic Spanish catalog structure:
//   Inicio · Mobiliario · Arquitecto · Economía · Mascotas · Wired
// Mobiliario = all general furni grouped by furni line; Arquitecto = Builders
// Club furni; Wired = wired furni; Mascotas mirrors the stock pet pages.
//
// Inputs (in .tmp/): es_furni.json (habbo.es metadata), items_base.tsv.
// Output: .tmp/catalog-build.sql  (idempotent, keyed on page_special='rtv2015').
import fs from "fs";

const ROOT = "E:/RetroTv/.tmp";
const es = JSON.parse(fs.readFileSync(`${ROOT}/es_furni.json`, "utf8"));
const meta = new Map(); // classname -> {bc, furniline, rare}
for (const sec of ["roomitemtypes", "wallitemtypes"]) {
  for (const f of es[sec]?.furnitype ?? []) {
    if (f.classname) meta.set(f.classname, { bc: f.bc === true, furniline: String(f.furniline || "").trim(), rare: f.rare === true });
  }
}

const items = fs.readFileSync(`${ROOT}/items_base.tsv`, "utf8").trim().split(/\r?\n/)
  .map((l) => { const i = l.indexOf("\t"); return { id: Number(l.slice(0, i)), cn: l.slice(i + 1) }; })
  .filter((x) => Number.isInteger(x.id) && x.cn);

// Pet pages to mirror under Mascotas (stock, authentic — copy their items).
const PETS = [75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,681,685];

// Nicer Spanish labels for common lines; otherwise Title-case the line code.
const LINE_ES = { classics:"Clásicos", rare:"Rares", bonusrare:"Rares Bonus", xmas:"Navidad", hween:"Halloween",
  easter:"Pascua", valentines:"San Valentín", summer:"Verano", duckets:"Duckets", diamond:"Diamante",
  habbo_club_gifts:"Regalos HC", iced:"Iced", pura:"Pura", plasto:"Plasto", wired:"Wired", otros:"Otros" };
const label = (l) => LINE_ES[l] || (l ? l.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) : "Otros");

// Classify each item into a tab + line bucket.
const buckets = { mob: new Map(), arq: new Map(), wired: [] }; // line -> items[]
for (const it of items) {
  const m = meta.get(it.cn) || { bc: false, furniline: "", rare: false };
  const isWired = it.cn.startsWith("wf_") || m.furniline === "wired";
  if (isWired) { buckets.wired.push(it); continue; }
  const tab = m.bc ? "arq" : "mob";
  const line = m.furniline || "otros";
  const map = buckets[tab];
  if (!map.has(line)) map.set(line, []);
  map.get(line).push({ ...it, rare: m.rare });
}

// Pages get explicit ids (so items can reference them); items auto-increment.
let pid = 1131;
const esc = (s) => String(s).replace(/'/g, "''");
const out = [];
out.push("-- Generated by scripts/build-catalog.mjs — authentic ES catalog. Idempotent.");
out.push("DELETE FROM catalog_items WHERE page_id IN (SELECT id FROM catalog_pages WHERE page_special='rtv2015');");
out.push("DELETE FROM catalog_pages WHERE page_special='rtv2015';");
out.push("UPDATE catalog_pages SET visible='0' WHERE page_special<>'rtv2015' OR page_special IS NULL;");

const COLS = "(id,parent_id,caption_save,caption,page_layout,icon_color,icon_image,min_rank,order_num,visible,enabled,club_only,catalog_mode,vip_only,page_special,page_headline,page_teaser,page_text1,page_text2,page_text_details,page_text_teaser)";
function page({ parent, caption, layout = "default_3x3", order, icon = 2, text1 = "" }) {
  const id = pid++;
  out.push(`INSERT INTO catalog_pages ${COLS} VALUES (${id},${parent},'${esc(caption)}','${esc(caption)}','${layout}',1,${icon},1,${order},'1','1','0','NORMAL','0','rtv2015','','','${esc(text1)}','','','');`);
  return id;
}
function addItems(pageId, list, { credits = 5, points = 0 } = {}) {
  for (const it of list) {
    const cr = it.rare ? 500 : credits;
    out.push(`INSERT INTO catalog_items (item_ids,page_id,catalog_name,cost_credits,cost_points,points_type,amount,order_number,club_only) VALUES ('${it.id}',${pageId},'${esc(it.cn)}',${cr},${points},0,1,${it.id},'0');`);
  }
}
// Build a tab whose lines become sub-pages; small lines fold into "Otros".
function buildLineTab(tabId, lineMap, { minPerPage = 8, opts = {} } = {}) {
  const lines = [...lineMap.entries()].sort((a, b) => b[1].length - a[1].length);
  const otros = [];
  let order = 1;
  for (const [line, list] of lines) {
    if (list.length < minPerPage) { otros.push(...list); continue; }
    const p = page({ parent: tabId, caption: label(line), order: order++, icon: 2 + (order % 26) });
    addItems(p, list, opts);
  }
  if (otros.length) { const p = page({ parent: tabId, caption: "Otros", order: order++, icon: 5 }); addItems(p, otros, opts); }
}

// ---- Tabs (top level) ----
const tInicio = page({ parent: -1, caption: "Inicio", layout: "frontpage", order: 1, icon: 213, text1: "¡Bienvenido al catálogo de RetroTV!" });
const tMob = page({ parent: -1, caption: "Mobiliario", order: 2, icon: 2 });
const tArq = page({ parent: -1, caption: "Arquitecto", order: 3, icon: 3 });
const tEco = page({ parent: -1, caption: "Economía", order: 4, icon: 4 });
const tMasc = page({ parent: -1, caption: "Mascotas", order: 5, icon: 6 });
const tWired = page({ parent: -1, caption: "Wired", order: 6, icon: 7 });

// ---- Mobiliario + Arquitecto (by line) ----
buildLineTab(tMob, buckets.mob, { minPerPage: 8 });
buildLineTab(tArq, buckets.arq, { minPerPage: 8 });

// ---- Wired ----
const wp = page({ parent: tWired, caption: "Wired", order: 1, icon: 7 });
addItems(wp, buckets.wired);

// ---- Economía ----
const pix = page({ parent: tEco, caption: "Tienda de Píxeles", order: 1, icon: 8 });
// stock the pixel shop with a sample of furni priced in duckets
addItems(pix, items.slice(0, 40).map((x) => ({ ...x, rare: false })), { credits: 0, points: 10 });
// Crafteo is omitted: this emulator build has no 'crafting' catalog page_layout
// (crafting is done via in-room altar furni). Ecotrón/Cambio skipped by choice.
page({ parent: tEco, caption: "Promociona Salas", layout: "roomads", order: 2, icon: 10 });

// ---- Mascotas: mirror stock pet pages (copy their items verbatim) ----
let po = 1;
for (const src of PETS) {
  const np = pid++;
  out.push(`INSERT INTO catalog_pages ${COLS} SELECT ${np},${tMasc},caption_save,caption,'pets',1,11,1,${po++},'1','1','0','NORMAL','0','rtv2015','','','','','','' FROM catalog_pages WHERE id=${src};`);
  out.push(`INSERT INTO catalog_items (item_ids,page_id,catalog_name,cost_credits,cost_points,points_type,amount,order_number,club_only) SELECT item_ids,${np},catalog_name,cost_credits,cost_points,points_type,amount,order_number,club_only FROM catalog_items WHERE page_id=${src};`);
}

fs.writeFileSync(`${ROOT}/catalog-build.sql`, out.join("\n") + "\n");
const pageCount = pid - 1131;
console.log(`pages: ${pageCount}  (Mobiliario lines:${buckets.mob.size} Arquitecto lines:${buckets.arq.size} wired:${buckets.wired.length})`);
console.log(`SQL -> ${ROOT}/catalog-build.sql`);
